### ISSUE TITLE
SQLSTATE[HY000] [2002] Connection refused when php artisan config:cache

### ISSUE THREAD

**Issue by cityuderek** [laravel-admin-extensions/config#33]
When running command:
php artisan config:cache;

Error:
   Illuminate\Database\QueryException 

  SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = clp and table_name = admin_config and table_type = 'BASE TABLE')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:670
    666|         // If an exception occurs when attempting to run a query, we'll format the error
    667|         // message to include the bindings with SQL, which will make this exception a
    668|         // lot more helpful to the developer instead of just the database's errors.
    669|         catch (Exception $e) {
  > 670|             throw new QueryException(
    671|                 $query, $this->prepareBindings($bindings), $e
    672|             );
    673|         }
    674|

  1   [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(App\Providers\AppServiceProvider))

      +1 vendor frames 
  3   [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(App\Providers\AppServiceProvider))

**Comment by cityuderek** [comment]
local.ERROR: SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = clp and table_name = admin_config and table_type = 'BASE TABLE') {"exception":"[object] (Illuminate\\Database\\QueryException(code: 2002): SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = clp and table_name = admin_config and table_type = 'BASE TABLE') at /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connection.php:670)
[stacktrace]
#0 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connection.php(744): Illuminate\\Database\\Connection->runQueryCallback('select * from i...', Array, Object(Closure))
#1 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connection.php(724): Illuminate\\Database\\Connection->tryAgainIfCausedByLostConnection(Object(Illuminate\\Database\\QueryException), 'select * from i...', Array, Object(Closure))
#2 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connection.php(633): Illuminate\\Database\\Connection->handleQueryException(Object(Illuminate\\Database\\QueryException), 'select * from i...', Array, Object(Closure))
#3 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connection.php(339): Illuminate\\Database\\Connection->run('select * from i...', Array, Object(Closure))
#4 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(18): Illuminate\\Database\\Connection->select('select * from i...', Array)
#5 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Database\\Schema\\MySqlBuilder->hasTable('admin_config')
#6 /Users/derek/clp-cms_git/app/Providers/AppServiceProvider.php(30): Illuminate\\Support\\Facades\\Facade::__callStatic('hasTable', Array)
#7 [internal function]: App\\Providers\\AppServiceProvider->boot()
#8 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#9 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#11 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#12 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#13 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(865): Illuminate\\Container\\Container->call(Array)
#14 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(848): Illuminate\\Foundation\\Application->bootProvider(Object(App\\Providers\\AppServiceProvider))
#15 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(App\\Providers\\AppServiceProvider), 22)
#16 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(849): array_walk(Array, Object(Closure))
#17 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#18 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(228): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#19 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#20 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Foundation/Console/ConfigCacheCommand.php(88): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#21 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Foundation/Console/ConfigCacheCommand.php(58): Illuminate\\Foundation\\Console\\ConfigCacheCommand->getFreshConfiguration()
#22 [internal function]: Illuminate\\Foundation\\Console\\ConfigCacheCommand->handle()
#23 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#24 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#25 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#26 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#27 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#28 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
#29 /Users/derek/clp-cms_git/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#30 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#31 /Users/derek/clp-cms_git/vendor/symfony/console/Application.php(912): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 /Users/derek/clp-cms_git/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Foundation\\Console\\ConfigCacheCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 /Users/derek/clp-cms_git/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#35 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#36 /Users/derek/clp-cms_git/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#37 {main}

[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Users/derek/clp-cms_git/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31)
[stacktrace]
#0 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(67): Doctrine\\DBAL\\Driver\\PDOConnection->__construct('mysql:host=127....', 'root', '', Array)
#1 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(100): Illuminate\\Database\\Connectors\\Connector->createPdoConnection('mysql:host=127....', 'root', '', Array)
#2 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(50): Illuminate\\Database\\Connectors\\Connector->tryAgainIfCausedByLostConnection(Object(Doctrine\\DBAL\\Driver\\PDOException), 'mysql:host=127....', 'root', '', Array)
#3 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection('mysql:host=127....', Array, Array)
#4 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(182): Illuminate\\Database\\Connectors\\MySqlConnector->connect(Array)
#5 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#6 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connection.php(925): call_user_func(Object(Closure))
#7 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connection.php(960): Illuminate\\Database\\Connection->getPdo()
#8 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connection.php(405): Illuminate\\Database\\Connection->getReadPdo()
#9 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connection.php(331): Illuminate\\Database\\Connection->getPdoForSelect(true)
#10 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connection.php(663): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('select * from i...', Array)
#11 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connection.php(744): Illuminate\\Database\\Connection->runQueryCallback('select * from i...', Array, Object(Closure))
#12 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connection.php(724): Illuminate\\Database\\Connection->tryAgainIfCausedByLostConnection(Object(Illuminate\\Database\\QueryException), 'select * from i...', Array, Object(Closure))
#13 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connection.php(633): Illuminate\\Database\\Connection->handleQueryException(Object(Illuminate\\Database\\QueryException), 'select * from i...', Array, Object(Closure))
#14 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connection.php(339): Illuminate\\Database\\Connection->run('select * from i...', Array, Object(Closure))
#15 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(18): Illuminate\\Database\\Connection->select('select * from i...', Array)
#16 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Database\\Schema\\MySqlBuilder->hasTable('admin_config')
#17 /Users/derek/clp-cms_git/app/Providers/AppServiceProvider.php(30): Illuminate\\Support\\Facades\\Facade::__callStatic('hasTable', Array)
#18 [internal function]: App\\Providers\\AppServiceProvider->boot()
#19 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#20 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#21 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#22 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#23 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#24 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(865): Illuminate\\Container\\Container->call(Array)
#25 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(848): Illuminate\\Foundation\\Application->bootProvider(Object(App\\Providers\\AppServiceProvider))
#26 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(App\\Providers\\AppServiceProvider), 22)
#27 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(849): array_walk(Array, Object(Closure))
#28 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#29 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(228): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#30 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#31 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Foundation/Console/ConfigCacheCommand.php(88): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#32 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Foundation/Console/ConfigCacheCommand.php(58): Illuminate\\Foundation\\Console\\ConfigCacheCommand->getFreshConfiguration()
#33 [internal function]: Illuminate\\Foundation\\Console\\ConfigCacheCommand->handle()
#34 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#35 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#36 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#37 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#38 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#39 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
#40 /Users/derek/clp-cms_git/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#41 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#42 /Users/derek/clp-cms_git/vendor/symfony/console/Application.php(912): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#43 /Users/derek/clp-cms_git/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Foundation\\Console\\ConfigCacheCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#44 /Users/derek/clp-cms_git/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#45 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#46 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#47 /Users/derek/clp-cms_git/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#48 {main}

[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /Users/derek/clp-cms_git/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)
[stacktrace]
#0 /Users/derek/clp-cms_git/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(27): PDO->__construct('mysql:host=127....', 'root', '', Array)
#1 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(67): Doctrine\\DBAL\\Driver\\PDOConnection->__construct('mysql:host=127....', 'root', '', Array)
#2 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(100): Illuminate\\Database\\Connectors\\Connector->createPdoConnection('mysql:host=127....', 'root', '', Array)
#3 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(50): Illuminate\\Database\\Connectors\\Connector->tryAgainIfCausedByLostConnection(Object(Doctrine\\DBAL\\Driver\\PDOException), 'mysql:host=127....', 'root', '', Array)
#4 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection('mysql:host=127....', Array, Array)
#5 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(182): Illuminate\\Database\\Connectors\\MySqlConnector->connect(Array)
#6 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#7 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connection.php(925): call_user_func(Object(Closure))
#8 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connection.php(960): Illuminate\\Database\\Connection->getPdo()
#9 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connection.php(405): Illuminate\\Database\\Connection->getReadPdo()
#10 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connection.php(331): Illuminate\\Database\\Connection->getPdoForSelect(true)
#11 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connection.php(663): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('select * from i...', Array)
#12 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connection.php(744): Illuminate\\Database\\Connection->runQueryCallback('select * from i...', Array, Object(Closure))
#13 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connection.php(724): Illuminate\\Database\\Connection->tryAgainIfCausedByLostConnection(Object(Illuminate\\Database\\QueryException), 'select * from i...', Array, Object(Closure))
#14 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connection.php(633): Illuminate\\Database\\Connection->handleQueryException(Object(Illuminate\\Database\\QueryException), 'select * from i...', Array, Object(Closure))
#15 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Connection.php(339): Illuminate\\Database\\Connection->run('select * from i...', Array, Object(Closure))
#16 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(18): Illuminate\\Database\\Connection->select('select * from i...', Array)
#17 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Database\\Schema\\MySqlBuilder->hasTable('admin_config')
#18 /Users/derek/clp-cms_git/app/Providers/AppServiceProvider.php(30): Illuminate\\Support\\Facades\\Facade::__callStatic('hasTable', Array)
#19 [internal function]: App\\Providers\\AppServiceProvider->boot()
#20 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#21 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#22 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#23 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#24 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#25 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(865): Illuminate\\Container\\Container->call(Array)
#26 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(848): Illuminate\\Foundation\\Application->bootProvider(Object(App\\Providers\\AppServiceProvider))
#27 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(App\\Providers\\AppServiceProvider), 22)
#28 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(849): array_walk(Array, Object(Closure))
#29 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#30 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(228): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#31 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#32 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Foundation/Console/ConfigCacheCommand.php(88): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#33 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Foundation/Console/ConfigCacheCommand.php(58): Illuminate\\Foundation\\Console\\ConfigCacheCommand->getFreshConfiguration()
#34 [internal function]: Illuminate\\Foundation\\Console\\ConfigCacheCommand->handle()
#35 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#36 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#37 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#38 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#39 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#40 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
#41 /Users/derek/clp-cms_git/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#42 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#43 /Users/derek/clp-cms_git/vendor/symfony/console/Application.php(912): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#44 /Users/derek/clp-cms_git/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Foundation\\Console\\ConfigCacheCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#45 /Users/derek/clp-cms_git/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#46 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#47 /Users/derek/clp-cms_git/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#48 /Users/derek/clp-cms_git/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#49 {main}
"}
